local:
  AUTH0_SIMPLE_TOKEN_KEY: local  # pragma: allowlist secret
  SECRET_KEY: local  # pragma: allowlist secret
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: storage
      NAME: service
      USER: service
      PASSWORD: password  # pragma: allowlist secret
test:
  AUTH0_SIMPLE_TOKEN_KEY: local  # pragma: allowlist secret
  SECRET_KEY: local  # pragma: allowlist secret
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3
