name: run-tests

on:
  push:

jobs:
  job-execute-tests:
    name: "Execute Cookiecutter tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Create project from template
        run: |
          cookiecutter . --no-input --output-dir /tmp/template
          cd /tmp/template
          ls -la
          python -m pip install -r requirements.txt

      - name: Create project from Cookiecutter template
        run: cookiecutter [путь к вашему шаблону] --no-input --output-dir /tmp/test_template

      - name: Install dependencies
        run: |
          cd /tmp/test_template/[имя созданного проекта]
          pip install -r requirements.txt

      - name: Run Docker Compose
        run: |
          cd /tmp/test_template/[имя созданного проекта]
          docker-compose up -d
