name: run-tests

on:
  push:

jobs:
  job-execute-tests:
    name: "Execute Cookiecutter tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Create project from template
        run: |
          cookiecutter . --no-input --output-dir /tmp
          cd /tmp/dummy
          python -m pip install -r requirements.txt

      - name: Run Docker Compose
        run: |
          ls -la
          docker compose up
